# Generated by Django 5.2 on 2025-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('category', models.CharField(choices=[('Flower', 'Flower'), ('Vegetable', 'Vegetable'), ('Tree', 'Tree')], max_length=255)),
                ('is_edible', models.BooleanField(default=False)),
                ('native_to', models.CharField(blank=True, max_length=255)),
                ('usage', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
