# Generated by Django 5.2.4 on 2025-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('native_to', models.CharField(max_length=200)),
                ('is_edible', models.BooleanField(default=False)),
                ('usage', models.TextField()),
                ('poster', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
