# Generated by Django 5.2.4 on 2025-07-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('HERB', 'Herb'), ('FLOWER', 'Flower'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('TREE', 'Tree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_edible',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plants.plant')),
            ],
        ),
    ]
