# Generated by Django 5.2.4 on 2025-07-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='category',
            field=models.CharField(choices=[('Algae', 'Algae'), ('Bryophytes', 'Bryophytes'), ('Pteridophytes', 'Pteridophytes'), ('Gymnosperms', 'Gymnosperms'), ('Angiosperms', 'Angiosperms')], default='Algae'),
        ),
    ]
