# Generated by Django 5.2.4 on 2025-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('FLOWER', 'Flower'), ('HERB', 'Herb'), ('TREE', 'Tree')], default='plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='/main/images/Plant-Holder-4.jpg', upload_to='plants/'),
        ),
    ]
