# Generated by Django 4.2.23 on 2025-07-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='plants',
            new_name='plant',
        ),
    ]
