# Generated by Django 5.2.4 on 2025-07-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_category_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('FLOWER', 'Flower'), ('HERB', 'Herb'), ('TREE', 'Tree'), ('UNKNOWN', 'PLANT')], default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
