# Generated by Django 4.2.23 on 2025-07-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_rename_plants_comment_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plants.plant'),
        ),
    ]
