# Generated by Django 5.2.4 on 2025-07-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('category', models.CharField(choices=[('Tree', 'Tree'), ('Shrub', 'Shrub'), ('Herb', 'Herb'), ('Vine', 'Vine'), ('Flower', 'Flower'), ('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Succulent', 'Succulent')], default='Tree', max_length=20)),
                ('is_edible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
