# Generated by Django 5.2.4 on 2025-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Flowers', 'Flowers'), ('Herb', 'Herb'), ('Tree', 'Tree'), ('cactus', 'cactus')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='plant',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
