# Generated by Django 5.2.4 on 2025-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('category', models.CharField(choices=[('Houseplant', 'Houseplant'), ('Herb', 'Herb'), ('Tree', 'Tree'), ('Shrub', 'Shrub'), ('Succulent', 'Succulent'), ('Other', 'Other')], max_length=20)),
                ('is_edible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
