# Generated by Django 5.2 on 2025-07-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='native_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='usage',
            field=models.TextField(blank=True),
        ),
    ]
