# Generated by Django 5.2 on 2025-07-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Flower', 'Flower'), ('Vegetable', 'Vegetable'), ('Tree', 'Tree')], max_length=255),
        ),
    ]
