# Generated by Django 5.2.3 on 2025-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plant')),
                ('about', models.TextField(default='Soon!')),
                ('used_for', models.TextField(default='Soon!')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='')),
                ('category', models.CharField(default='Fruit')),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
